# Generated by Django 4.2.13 on 2024-08-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuron", "0002_imageprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageprediction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
